require "aspiras.plugins-setup"
require "aspiras.core.options"
require "aspiras.core.keymaps"
require "aspiras.plugins.nvim-tree"
require "aspiras.core.colorscheme"
require "aspiras.plugins.lualine"

require "aspiras.plugins.nvim-cmp"
require "aspiras.plugins.lsp.mason"
require "aspiras.plugins.lsp.lspsaga"
require "aspiras.plugins.lsp.lspconfig"
require "aspiras.plugins.lsp.null-ls"
